name: Get Merged Branch Name

on: push

jobs:
  get_branch_name:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Extract branch name
      shell: bash
      run: echo "branch=${GITHUB_REF}" >> $GITHUB_OUTPUT
      id: getBranch

    - name: Print Merged Branch Name
      run: echo "Merged branch: $BASENAME"
      env:
        BASENAME: ${{ steps.getBranch.outputs.branch }}