name: Get Merged Branch Name

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  get_branch_name:
    runs-on: ubuntu-latest
    steps:
    
    - name: Print Merged Branch Name
      run: echo "REF_NAME $REF_NAME and HEAD_REF $HEAD_REF"
      env:
        REF_NAME: ${{ github.ref }}
        HEAD_REF: ${{ github.head_ref }}

