name: Get Merged Branch Name

on: push

jobs:
  get_branch_name:
    runs-on: ubuntu-latest
    steps:
    
    - name: Extract branch name
      shell: bash
      run: echo "branch=${GITHUB_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      id: getBranch

    - name: Print Merged Branch Name
      run: echo "Merged branch $NAME"
      env:
        REF_NAME: ${{ github_ref }}
        HEAD_REF: ${{ github.head_ref }}

